name: MyAction
on:
  push:
    branches:
      - main #here we choose to deploy only when a push is detected on the develop branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build static site
        run: npm install && npm run build && npm run generate

        run: echo "YES"
