name: MyAction
# Only trigger, when the generate workflow succeeded
on:
  workflow_run:
    workflows: ["generateAction"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build static site
        run: npm install && npm run build && npm run generate
      - name: log
        run: echo "YES"
